import { MetadataRoute } from "next";
import studies from "@/data/studies.json";

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = "https://austinmander.com";

  // Generated by scripts/sync-studies.mjs. Held pieces are absent from the
  // manifest by design, so they never reach the sitemap.
  const studyEntries: MetadataRoute.Sitemap = studies.published.map(
    (piece) => ({
      url: `${baseUrl}${piece.href}`,
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.6,
    })
  );

  return [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${baseUrl}/studies`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    ...studyEntries,
    {
      url: `${baseUrl}/privacy`,
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${baseUrl}/terms`,
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
    {
      url: `${baseUrl}/cookies`,
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.3,
    },
  ];
}
